engines:
  csslint:
    enabled: true
    checks:
      important:
        enabled: false
      box-sizing:
        enabled: false
  duplication:
    enabled: true
  eslint:
    enabled: true
    config:
      languages:
      - javascript
      extensions:
      - .js
      - .jsx
    checks:
      import/no-unresolved:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths:
- node_modules/
- server/test/
- client/test
- usr/local/node_modules/babel-eslint/index.js
- coverage/
- docs/
- db/
