language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm test
  - make test-coveralls
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls --verbose

after_success: 
  - npm run coveralls

after_script: 
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R server/tests/ && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

notifications:
  email:
    recipients:
      - oluwafemi.akinwa@andela.com
      - kaiser.phemi@protonmail.ch
  slack:
    rooms:
      - andela: KtLgTrjrNVcoO1cr9tCjYcEh
    on_success: change # default: always
    on_failure: always # default: always